name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install -g vercel

      #      - name: Run tests
      #        run: npm run test

      - name: Deploy to Vercel
        run: |
          if [[ ${{ job.status }} != 'success' ]]; then
            echo "Tests failed or encountered errors. Changes will not be merged to main."
            exit 1
          else
            git fetch --all
            git checkout main
            git config user.name "$(git --no-pager show -s --format='%an' ${{ github.event.pull_request.head.sha }})"
            git config user.email "$(git --no-pager show -s --format='%ae' ${{ github.event.pull_request.head.sha }})"
            git commit --amend --no-edit
            git merge --no-ff origin/dev
            git push origin main
          fi
