name: Merge to main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm run test

      - name: Set git user
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Merge origin/dev into main
        run: |
          if [[ ${{ job.status }} != 'success' ]]; then
            echo "Tests failed or encountered errors. Changes will not be merged to main."
            exit 1
          else
            git fetch --all
            git fetch origin dev
            git checkout main
            git merge --no-ff origin/dev
            git commit --amend --no-edit
            git push origin main
          fi

      - name: Push changes to main
        run: git push origin main

  deploy-to-production:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
